baseURL = "http://blog.icarus4.com/"
languageCode = "zh-TW"
title = "icarus4"
theme = "cactus"
publishDir = "docs"
googleAnalytics = "UA-47031561-1"
disqusShortname = "icarus4"
hasCJKLanguage = true

[taxonomies]
tag = "tags"
category = "categories"

[params]
	name = "icarus4"
	description = "Programmer and many more"
	bio = "Programmer and many more"
	# Enter optionally your twitter account
	# twitter = "Your Twitter account"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Programmer and many more"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/icarus4chu"
    facebook = "https://www.facebook.com/icarus4.chu"
    github   = "https://github.com/icarus4"
    # dribble  = "https://www.dribbble.com/"
